name: Simple Scan Workflow
 
on: 
  push:
 
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 20 seconds
        run: sleep 20
      - name: Print scan  message
        run: echo "Scanning code job"  
