name: Simple Test Workflow
 
on: 
  push:
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 10 seconds
        run: sleep 10
      - name: Print test message
        run: echo "Testing code job"
